name: Code quality checks

on:
  push:
    branches:
      - '**'
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  pull-requests: read
  packages: read

jobs:
  build:

    runs-on: ubuntu-24.04

    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Cache dependencies
      uses: actions/cache@v4
      env:
        cache-name: cache-node-modules
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        # https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Lint
      id: lint
      run: npm run lint

    - name: Run tests
      id: tests
      run: npm run test:ci
